Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [15]:
import numpy as np
def vandermonde_matrix(inputvector, n, increasing=False):
    
    if not increasing:
        output_matrix = np.array([x**(n-1-i) for x in inputvector for i in range(n)]).reshape(inputvector.size,n)
    elif increasing:
        output_matrix = np.array([x**i for x in inputvector for i in range(n)]).reshape(inputvector.size,n)
    
    return output_matrix
inputvector = np.array([1,2,3,4,5])
no_col_opmat = 5
output_matrix_dec_order = vandermonde_matrix(inputvector,no_col_opmat,False)
output_matrix_inc_order = vandermonde_matrix(inputvector,no_col_opmat,True)

print("input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order:\n\n",output_matrix_dec_order,"\n")
print("Vander matrix of the input array in increasing order:\n\n",output_matrix_inc_order,"\n")


input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 5 

Vander matrix of the input array in decreasing order:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

Vander matrix of the input array in increasing order:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 



Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [6]:
mylist = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
N = 4

mov_avg_val(mylist,N)

Moving average values list:  [25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]
Length of the list l-N+1:  7


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
def mov_avg_val(mylist, N):
    sum_up, moving_aves = [0], []
    for i, x in enumerate(mylist, 1):
        sum_up.append(sum_up[i-1] + x)
        if i>=N:
            moving_average = round(((sum_up[i] - sum_up[i-N])/N),2)
            moving_aves.append(moving_average)
    print("Moving average values list: ", moving_aves)
    print("Length of the list l-N+1: ", len(moving_aves))

In [5]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3

mov_avg_val(mylist,N)

Moving average values list:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the list l-N+1:  11
